/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/billing/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Health check endpoint */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/v2/teams/{teamId}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get usage and credit balance for a team */
        get: operations["getUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/teams/{teamId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get tiers and addons for a team */
        get: operations["getItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/teams/{teamId}/billing-limits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get billing limits for a team */
        get: operations["getBillingLimits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Update billing limits for a team */
        patch: operations["updateBillingLimits"];
        trace?: never;
    };
    "/billing/teams/{teamId}/billing-limits/{type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Delete a specific billing limit */
        delete: operations["deleteBillingLimit"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/checkouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create a checkout session (MVP returns mailto link) */
        post: operations["createCheckout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/stripe/portal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Get Stripe customer portal URL (MVP returns mailto link) */
        post: operations["stripePortal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/teams/{teamId}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create an addon order (not implemented in MVP) */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/teams/{teamId}/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Confirm an addon order (not implemented in MVP) */
        post: operations["confirmOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/teams/{teamId}/payment-methods/customer-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Get Stripe customer session for payment methods (not implemented in MVP) */
        post: operations["getCustomerSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/teams/{teamId}/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get invoices for a team */
        get: operations["getInvoices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /**
             * Format: int32
             * @description Error code
             */
            code: number;
            /** @description Error message */
            message: string;
        };
        HealthResponse: {
            /** @description Health status */
            status: string;
            /** @description Service name */
            service: string;
        };
        BillingLimit: {
            /** @description Spending limit threshold in cents */
            limit_amount_gte: number | null;
            /** @description Alert threshold in cents */
            alert_amount_gte: number | null;
        };
        BillingLimitUpdate: {
            /** @description Spending limit threshold in cents */
            limit_amount_gte?: number | null;
            /** @description Alert threshold in cents */
            alert_amount_gte?: number | null;
        };
        CustomerPortalResponse: {
            /** @description URL to redirect to (Stripe portal or mailto link) */
            url: string;
        };
        DayUsage: {
            /** @description Date in YYYY-MM-DD format */
            date: string;
            /**
             * Format: int64
             * @description Number of sandboxes created
             */
            sandbox_count: number;
            /**
             * Format: double
             * @description Total CPU hours used
             */
            cpu_hours: number;
            /**
             * Format: double
             * @description Total RAM GiB-hours used
             */
            ram_gib_hours: number;
            /**
             * Format: double
             * @description Cost for RAM usage in dollars
             */
            price_for_ram: number;
            /**
             * Format: double
             * @description Cost for CPU usage in dollars
             */
            price_for_cpu: number;
        };
        HourUsage: {
            /**
             * Format: int64
             * @description Unix timestamp in seconds
             */
            timestamp: number;
            /**
             * Format: int64
             * @description Number of sandboxes created
             */
            sandbox_count: number;
            /**
             * Format: double
             * @description Total CPU hours used
             */
            cpu_hours: number;
            /**
             * Format: double
             * @description Total RAM GiB-hours used
             */
            ram_gib_hours: number;
            /**
             * Format: double
             * @description Cost for RAM usage in dollars
             */
            price_for_ram: number;
            /**
             * Format: double
             * @description Cost for CPU usage in dollars
             */
            price_for_cpu: number;
        };
        UsageResponse: {
            /**
             * Format: double
             * @description Current credit balance in dollars
             */
            credits: number;
            /** @description Daily usage breakdown */
            day_usages: components["schemas"]["DayUsage"][];
            /** @description Hourly usage breakdown (last 24 hours) */
            hour_usages: components["schemas"]["HourUsage"][];
        };
        TierLimits: {
            /** @description Maximum concurrent sandboxes */
            sandbox_concurrency: number;
            /** @description Maximum vCPUs per sandbox */
            max_cpu: number;
            /** @description Maximum RAM in MiB per sandbox */
            max_ram_mib: number;
            /** @description Maximum sandbox duration in hours */
            max_sandbox_duration_hours: number;
            /** @description Disk size in MiB per sandbox */
            disk_size_mib: number;
        };
        TierInfo: {
            /** @description Tier identifier (e.g., base_v1, pro_v1) */
            id: string;
            /** @description Display name (e.g., Hobby, Pro) */
            name: string;
            /** @description Monthly price in cents (0 for pay-as-you-go) */
            price_cents: number;
            limits?: components["schemas"]["TierLimits"];
        };
        AddonInfo: {
            /** @description Addon identifier */
            id: string;
            /** @description Display name */
            name: string;
            /** @description Price in cents */
            price_cents: number;
            /** @description Quantity purchased (if applicable) */
            quantity?: number;
        };
        TeamAddons: {
            /** @description Currently active addons */
            current: components["schemas"]["AddonInfo"][];
            /** @description Available addons for purchase */
            available: components["schemas"]["AddonInfo"][];
        };
        TeamTiers: {
            /** @description Current tier ID */
            current: string;
            /** @description Available tiers */
            available: components["schemas"]["TierInfo"][];
        };
        TeamItems: {
            tiers: components["schemas"]["TeamTiers"];
            addons: components["schemas"]["TeamAddons"];
        };
        AddOnOrderItem: {
            /** @description Addon identifier */
            name: string;
            /** @description Quantity to purchase */
            quantity: number;
        };
        AddOnOrderCreateRequest: {
            items: components["schemas"]["AddOnOrderItem"][];
        };
        AddOnOrderCreateResponse: {
            /** @description Order ID */
            id: string;
            /** @description Amount due in cents */
            amount_due: number;
            items: components["schemas"]["AddOnOrderItem"][];
        };
        AddOnOrderConfirmResponse: {
            /** @description Stripe client secret for payment confirmation */
            client_secret: string;
        };
        PaymentMethodsCustomerSession: {
            /** @description Stripe customer session client secret */
            client_secret: string;
        };
        Invoice: {
            /**
             * Format: double
             * @description Invoice amount
             */
            cost: number;
            /** @description Whether invoice is paid */
            paid: boolean;
            /** @description URL to view/pay invoice */
            url: string;
            /** @description Creation date */
            date_created: string;
        };
        CreateTeamsResponse: {
            /** @description Team ID */
            id: string;
            /** @description Team slug */
            slug: string;
        };
        CheckoutRequest: {
            /** @description Team ID */
            teamID: string;
            /** @description Target tier ID */
            tierID: string;
        };
    };
    responses: {
        /** @description Bad request */
        400: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authentication error */
        401: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Payment required */
        402: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Forbidden */
        403: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Server error */
        500: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not implemented */
        501: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        teamId: string;
        orderId: string;
        limitType: "limit_amount_gte" | "alert_amount_gte";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getUsage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully returned usage data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageResponse"];
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            500: components["responses"]["500"];
        };
    };
    getItems: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully returned team items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamItems"];
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            500: components["responses"]["500"];
        };
    };
    getBillingLimits: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully returned billing limits */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingLimit"];
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            500: components["responses"]["500"];
        };
    };
    updateBillingLimits: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BillingLimitUpdate"];
            };
        };
        responses: {
            /** @description Successfully updated billing limits */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            500: components["responses"]["500"];
        };
    };
    deleteBillingLimit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                type: components["parameters"]["limitType"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully deleted billing limit */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            500: components["responses"]["500"];
        };
    };
    createCheckout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutRequest"];
            };
        };
        responses: {
            /** @description Successfully created checkout */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerPortalResponse"];
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            500: components["responses"]["500"];
        };
    };
    stripePortal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully got portal URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerPortalResponse"];
                };
            };
            401: components["responses"]["401"];
            500: components["responses"]["500"];
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddOnOrderCreateRequest"];
            };
        };
        responses: {
            /** @description Successfully created order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddOnOrderCreateResponse"];
                };
            };
            501: components["responses"]["501"];
        };
    };
    confirmOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                orderId: components["parameters"]["orderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully confirmed order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddOnOrderConfirmResponse"];
                };
            };
            501: components["responses"]["501"];
        };
    };
    getCustomerSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully got customer session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentMethodsCustomerSession"];
                };
            };
            501: components["responses"]["501"];
        };
    };
    getInvoices: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully returned invoices */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invoice"][];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            500: components["responses"]["500"];
        };
    };
}
